USGCRP/gcis

lib/Tuba/files/templates/table/object.ttl.tut

The report in which the table is housed was previously not showing up.  This fixes it, and was successfully tested.

Moved table->report line

---

lib/Tuba/files/templates/doc/about.html.ep

"number" in "ISBN number" is redundant.

Removed redundant "numbers"

---

lib/Tuba/files/templates/other_identifiers.ttl.tut

consistent pattern has been <URI> . not <URI>.

extra space for consistency

---

lib/Tuba/files/templates/thumbs.html.ep

This table tag and caption tags were also causing the sticky footer to not work correctly in Chrome.

Deleted empty table and caption tags from thumbs.html.ep

---

lib/Tuba/files/public/css/gcis.css

This fixes the scroll bar being displayed on all pages in Firefox.

Deleted padding-top rule for #footer div.

---

lib/Tuba/files/templates/activity/object.ttl.tut

Updated template to create a qualified association for the software agent and methodology employed in this activity.
Fixes USGCRP/gcis-ontology/issues/9.
note - I know we are probably not ready to merge this pull request yet.  I am creating it so we can see what the changes to the template would look like and discuss.

added qualifiedAssociation for software agent

---

lib/Tuba/files/templates/dataset/object.ttl.tut

based on http://www.essepuntato.it/lode/http://purl.org/spar/datacite#introduction the property to reference a datacite:AlternateResourceIdentifier would be datacite:hasIdentifier.
We can optionally include a datacite:usesIdentifierScheme here if one is known.

update datacite:AlternateResourceIdentifier usage

---

lib/Tuba/files/templates/chapter/object.ttl.tut

Note: I recognize that the presence of bibo:doi could make gcis:hasURL redundant.  However, this isn't trivial for the NCA3 since the url directs one to the web version of that document, while the other to the download page.  (Fine with me, of course).  Of course this won't hold true for all "chapters" in GCIS.  If including both "doi" and "hasURL" is problematic, let me know and I'll create an issue in gethub.

Added doi to turtle for chapters

---

lib/Tuba/files/templates/doc/about.html.ep

Given that Stephan, like Marshall, has led the ontology development efforts, we should call him out as well.

Called out Stephan

---

lib/Tuba/files/templates/role_type/object.ttl.tut

Basic turtle, can expand later.  Replaces current template which ends in a semicolon.

Turtle for role_types

---

lib/Tuba/files/templates/gcmd_keyword/object.ttl.tut

Took an initial stab so that the turtle for GCMD_keywords reads in a grammatically correct manner.  Development will be ongoing.

Initial turtle for keywords

---

lib/Tuba/files/templates/article/object.ttl.tut

In order to accommodate the change from gcis:Article to gcis:AcademicArticle in the Ontology.  See:
https://github.com/USGCRP/gcis-ontology/pull/65

gcis:Article -> gcis:AcademicArticle

---

lib/Tuba/files/templates/reference/object.ttl.tut

Removed due to it being a property in-lieu of a class.

Removed dcterms:bibliographicCitation

---

lib/Tuba/files/templates/instrument_instance/object.ttl.tut

references USGCRP/gcis-ontology/issues/124.
This type is inferable from the domain of prov:contributed; adding it to the template to make the type information explicit without requiring reasoning.

add type prov:Agent to instrument instances

---

lib/Tuba/files/templates/lexicon/object.ttl.tut

Mentioned in USGCRP/gcis-ontology/issues/35, dbpedia:Lexicon is not a class but an instance and should not be used a type.

remove type dbpedia:Lexicon

---

lib/Tuba/files/templates/model_run/object.ttl.tut

I think we may want to add a property to the ontology for the model scenario 
``<<%= uri($model_run->scenario) %>>``
The only scenario properties in the ontology are
```
gcis:Scenario a owl:Class ;
rdfs:label "Scenario" ;
rdfs:comment "Sets of assumptions used to help understand potential future conditions such as population growth, land use, and sea level rise. Scenarios are neither predictions nor forecasts. Scenarios are commonly used for planning purposes." ;
rdfs:subClassOf prov:Entity .
gcis:describesScenario a owl:ObjectProperty ;
rdfs:label "describes scenario" ;
rdfs:comment "A resource may describe one or more scenarios." ;
rdfs:range gcis:Scenario ;
owl:inverseOf gcis:scenarioDescribedIn .
gcis:scenarioDescribedIn a owl:ObjectProperty ;
rdfs:label "is described in" ; …
```

update predicates and type for model run output RDF

---

lib/Tuba/files/templates/model/object.ttl.tut

references USGCRP/gcis-ontology/issues/96

update template to say model wasAttributedTo project

---

lib/Tuba/files/templates/webpage/object.html.ep

Allows the host of the website to show up in the html.  Earlier this was restricted to reports, not websites.

Permit website hosts to show up

---

db/patches/2190_morerels.sql

Builds on patches 0780 and 0830.
Rationale: feedback that university institutes should really be "centers of" instead of "program of."

Added "center of"

---

Build.PL
META.json
META.yml

This locks the Mojolicious version to the last known good version of 6.24 where builds did not fail Travis tests on (unmodified) Tuba.pm
Technically, the change allows for any version between 6.08 and 6.24, but cpanm always pulls the most recent version available/allowed.

Lock Mojo Version <= 6.24

---

lib/Tuba/files/templates/organization/object.ttl.tut

See Section 2.4 at: https://www.w3.org/TR/vocab-org/ (last accessed 6/19/16).  The proper way to relate organizations to their predecessors is through "prov:wasDerivedAs."

Added condition for predecessor orgs

---

db/patches/2260_alter_pubs_desc_title.sql
lib/Tuba/Chapter.pm
lib/Tuba/DB/Mixin/Object/Dataset.pm
lib/Tuba/DB/Mixin/Object/Finding.pm
lib/Tuba/DB/Mixin/Object/Generic.pm
lib/Tuba/DB/Mixin/Object/Reference.pm
lib/Tuba/Dataset.pm
lib/Tuba/Figure.pm
lib/Tuba/files/templates/article/object.html.ep
lib/Tuba/files/templates/article/object.ttl.tut
t/009_article.t

In support of #369:
- `Chapter` now has a `description` field that is return via the json API.
- `Figure` json API returns a `description`, which is an alias for the existing `caption`
- `Finding` json API returns a `description`, which is an alias for the existing `statement`
- `Journal` now has a `description` field that is returned via the json API.
- `Article` now has a `description` field that is
- returned via the json API
- displayed via the html requests, if it is populated
- is returned as in the turtle as `dcterms:description`
- `Webpage` now has a `description` field that is returned via the json API.
- `Book` now has a `description` field that is returned via the json API.
- `Dataset` now has a `description` field that is returned via the json API.

Merge in display_name & description support

---

.travis.yml

In migrating from postgres 9.2 to 9.3, the required packages changed to include the `server` package. made the requirements for travis more robust in general.

Fix travis build post Postgres9.2 EoL

---

lib/Tuba/Controller.pm
lib/Tuba/files/templates/h/other_formats.html.ep

- GCIS Arrays can now return their content formatted as CSV (#601)
- Supports user feedback & NCA4 needs.

GCIS v1.54.0

---

lib/Tuba/Controller.pm

This change returns a JSON block instead of a simple identifier string.

Modify Controller.pm to return JSON from put_files

---

lib/Tuba.pm

The origination code is specific to figure. The report-level figures are of a different type "report_figure". I've added the origination methods to the report_figure object. Feel free to reject and make the change differently. I'm not familiar enough with the code base to evaluate if this is an ideal fix. Testing in data-tsu indicates that GET and POST are now working for report-level figures.

Adding origination code to handle report_figure. Addresses issue #695
