USGCRP/gcis

lib/Tuba/files/templates/generic/object.ttl.tut, lib/Tuba/files/templates/other_identifiers.ttl.tut, lib/Tuba/files/templates/reference/object.ttl.tut
(Otherwise difficult to read when multiple lexicons are utilized to describe the same entity)
=> added extra line to improve readability in other_identifiers.ttl.tut

lib/Tuba/files/templates/instrument_instance/object.ttl.tut
for output readability purposes
=> spacing in instrument_instance turtle

lib/Tuba/files/templates/array/object.ttl.tut
=> spacing in turtle for arrays

README.osx
Added two lines to item #13 about how you might have to run a postgres command before the morbo command.
=> Added two lines to #14 in README.osx file

lib/Tuba/files/templates/index.html.ep
SVG image height decreased.
GCIS spellout font color changed to dark blue.
H2 tags, "About", "Examples", font size decreased.
Row with the above H2 tags positioned slightly more to the left.
=> Edits made to GCIS home page.

lib/Tuba/files/templates/index.html.ep
Links in svg have numbers in parnethese.
Links in svg are a blue "link" color.
Class for svg image is changed to span8 with an offset -- moves better.
CSS (internal -- index.html.ep file) is edited.
=> Edited front page svg image bootstrap and links, and bottom footer

lib/Tuba/files/templates/index.html.ep
Labels for JSON and YAML positioned under svg image.
=> Front page svg font size edited, now 0.5em instead of a px value.

lib/Tuba/files/templates/dataset/object.html.ep, lib/Tuba/files/templates/h/leaflet.html.ep, lib/Tuba/files/templates/h/thumbnail.html.ep, lib/Tuba/files/templates/image/object.html.ep
This pull request merges in various improvements to the leaflet integration into GCIS.
=> various improvements to leaflet integration

lib/Tuba/files/templates/h/leaflet.html.ep, lib/Tuba/files/templates/h/thumbnail.html.ep, lib/Tuba/files/templates/image/object.html.ep
Here's this mornings updates.
Thanks,
Gerald
=> improve wrap around and handle 0 values

lib/Tuba/files/templates/collapsible.html.ep, lib/Tuba/files/templates/create_form.html.ep, lib/Tuba/files/templates/history_modal.html.ep, lib/Tuba/files/templates/layouts/default.html.ep, lib/Tuba/files/templates/messages.html.ep, lib/Tuba/files/templates/obj_thumbnails.html.ep, lib/Tuba/files/templates/prov.html.ep
The "X" to close modal window -- history_modal.html.ep -- is not showing.
=> Helper files edited, some problems left with histiory_modal.

lib/Tuba/files/public/css/gcis.css, lib/Tuba/files/templates/layouts/default.html.ep, lib/Tuba/files/templates/layouts/front.html.ep, lib/Tuba/files/templates/prov.html.ep
The footers work correctly.
The footer is not added to body (parent) div on page Figures page, but still works correctly.
=> Sticky footer html and css adds.

lib/Tuba/files/templates/create_form.html.ep, lib/Tuba/files/templates/update_form.html.ep
Here's Justin's request, Brian.
=> allow user to specify no header rows

lib/Tuba/files/public/css/gcis.css, lib/Tuba/files/templates/article/object.html.ep, lib/Tuba/files/templates/book/object.html.ep, lib/Tuba/files/templates/dataset/object.html.ep, lib/Tuba/files/templates/figure/objects.html.ep, lib/Tuba/files/templates/image/object.html.ep, lib/Tuba/files/templates/index.html.ep, lib/Tuba/files/templates/instrument/object.html.ep, lib/Tuba/files/templates/instrument_instance/object.html.ep, lib/Tuba/files/templates/journal/object.html.ep, lib/Tuba/files/templates/layouts/default.html.ep, lib/Tuba/files/templates/layouts/front.html.ep, lib/Tuba/files/templates/lexicon/object.html.ep, lib/Tuba/files/templates/model/object.html.ep, lib/Tuba/files/templates/objects.html.ep, lib/Tuba/files/templates/organization/object.html.ep, lib/Tuba/files/templates/organization/objects.html.ep, lib/Tuba/files/templates/organization/update_form.html.ep, lib/Tuba/files/templates/person/object.html.ep, lib/Tuba/files/templates/person/objects.html.ep, lib/Tuba/files/templates/platform/object.html.ep, lib/Tuba/files/templates/pub_thumbnails.html.ep, lib/Tuba/files/templates/report/object.html.ep, lib/Tuba/files/templates/scenario/object.html.ep, lib/Tuba/files/templates/webpage/object.html.ep
Only one "container" class per page now.  (Can't be nested.)
=> Cleaning up bootstrap 3 classes and Peple and Organizations pages.

lib/Tuba/files/templates/image/object.ttl.tut
To reflect commit 16f6440ddb7d8ee4d6701fcd4259f2a7b16a4886
=> turtle rep. for usage limits for image

lib/Tuba/files/templates/other_identifiers.ttl.tut, t/011_sparql.t
SameAs->sameAs in sparqltest
owl:SameAs->owl:sameAs
=> owl:SameAs->owl:sameAs

lib/Tuba/files/templates/activity/object.ttl.tut
Fixes USGCRP/gcis-ontology/issues/8
based on RDF publishing guidelines from http://wiki.dublincore.org/index.php/User_Guide/Publishing_Metadata#dcterms:extent
=> dcterms:SizeOrDuration -> dcterms:extent

lib/Tuba/files/templates/figure/object.ttl.tut, lib/Tuba/files/templates/image/object.ttl.tut
=> Employed recommendation of Issue #154

lib/Tuba/files/templates/activity/object.ttl.tut
Checks for software and methodology values before creating of PROV qualified association and plan relationships.
=> checks for values for software and methodology

lib/Tuba/files/templates/activity/object.ttl.tut
fixed incorrect PROV class name.
=> prov:QualifiedAssociation -> prov:Association

lib/Tuba/files/templates/other_identifiers.ttl.tut
=> updated property to reference skos concept

lib/Tuba/files/public/owl/gcis.ttl
=> Replaced typo in version in gcis repo

lib/Tuba/files/templates/activity/object.ttl.tut
=> Added gcis:computingEnvironmentsUsed

lib/Tuba/files/templates/other_identifiers.ttl.tut, lib/Tuba/files/templates/representation.ttl.tut
skos:altLabel -> skos:prefLabel
=> Per https://github.com/USGCRP/gcis/issues/165

lib/Tuba/files/templates/report/object.ttl.tut
closes USGCRP/gcis-ontology/issues/62
=> use dcterms:spatial for region information related to publication

lib/Tuba/files/templates/region/object.ttl.tut
=> dcterms:Relation -> dcterms:relation

lib/Tuba/files/templates/dataset/object.ttl.tut
references USGCRP/gcis-ontology/issues/22
=> replaced gcis:accessUrl with dcat:landingPage

lib/Tuba/files/templates/person/object.ttl.tut
Addresses:
https://github.com/USGCRP/gcis-ontology/issues/58
=> gcis:hasURL -> foaf:page for person

lib/Tuba/files/templates/organization/object.ttl.tut
Resolves https://github.com/USGCRP/gcis-ontology/issues/59
=> org:Purpose->dbpprop:organizationType

lib/Tuba/files/templates/region/object.ttl.tut
Per https://github.com/USGCRP/gcis-ontology/pull/88
=> dbpedia:Region -> gcis:Region

lib/Tuba/files/templates/image/object.ttl.tut
Addresses https://github.com/USGCRP/gcis-ontology/issues/10
=> Temporal coverage of image

lib/Tuba/files/templates/dataset/object.ttl.tut
Per https://github.com/USGCRP/gcis-ontology/issues/12
=> gcis:TemporalExtents->dcterms:temporal

lib/Tuba/files/templates/instrument_instance/object.ttl.tut
Per https://github.com/USGCRP/gcis-ontology/issues/35
=> instrument_instance ->gcis:Instrument

lib/Tuba/files/templates/instrument/object.ttl.tut
Per https://github.com/USGCRP/gcis-ontology/issues/35
=> gcis:Instrument -> gcis:InstrumentType

lib/Tuba/files/templates/file/object.ttl.tut
Per https://github.com/USGCRP/gcis-ontology/issues/19
=> Reformatted sha-1 and MIME

lib/Tuba/files/templates/finding/object.ttl.tut
Per https://github.com/USGCRP/gcis-ontology/issues/83  and https://github.com/USGCRP/gcis-ontology/pull/91
=> dcterms:description -> gcis:findingStatement

lib/Tuba/files/templates/finding/object.ttl.tut
Addresses https://github.com/USGCRP/gcis-ontology/issues/95.
=> Removed natural number

lib/Tuba/files/templates/platform/object.ttl.tut
Resolves https://github.com/USGCRP/gcis-ontology/issues/68
=> gcis:hasURL->dcterms:source for platforms

lib/Tuba/files/templates/article/object.ttl.tut, lib/Tuba/files/templates/book/object.ttl.tut, lib/Tuba/files/templates/report/object.ttl.tut
I thought this would be a better fit since we're only recording the four digit year in various triples.
=> dbpprop:pubDate -> dbpprop:pubYear

lib/Tuba/files/templates/instrument_instance/object.ttl.tut
Changed 
- ``gcis:Platform`` to ``gcis:inPlatform``
- ``gcis:Instrument`` to ``gcis:instrumentType``
- ``gcis:Dataset`` to ``prov:contibuted`` (recommended inverse property to ``prov:wasAttributedTo``)
=> Updated properties used in Instrument individuals

lib/Tuba/files/templates/dataset/object.ttl.tut, t/011_sparql.t
references USGCRP/gcis-ontology/issues/124
=> use prov:wasAttributedTo to link dataset with instrument

lib/Tuba/files/templates/file/object.ttl.tut
Addresses https://github.com/USGCRP/gcis-ontology/issues/108
=> schema:isRelatedTo->frbr:embodimentOf

lib/Tuba/files/templates/book/object.ttl.tut, lib/Tuba/files/templates/chapter/object.ttl.tut
@bduggan please do not merge until @zednis confirms whether or not these are appropriate additions.
http://vocab.ox.ac.uk/fabio#term_Book
http://vocab.ox.ac.uk/fabio#term_Chapter
Thanks!
=> Added possible fabio relation

lib/Tuba/files/templates/dataset/object.ttl.tut
Per: https://github.com/USGCRP/gcis-ontology/issues/72
=> Spatial and temporal extent fixes

lib/Tuba/files/templates/figure/object.ttl.tut, lib/Tuba/files/templates/image/object.ttl.tut
Addresses https://github.com/USGCRP/gcis-ontology/issues/77.
=> added fabio:Image, doco:Figure

lib/Tuba/Doc.pm
Lines 29-37 contain the updated code.
=> Locate->identify in new ex. 2

.travis.yml, lib/Tuba/files/templates/dataset/object.ttl.tut, t/017_person_api.t
xsd:date->xsd:dateTime on line 32
=> fixed mischaracterization of xsd:date

lib/Tuba/files/templates/dataset/object.ttl.tut
for purposes of virtuoso ingest
=> Conditional dcat:landingPage

lib/Tuba/files/templates/dataset/object.ttl.tut
=> Added "biro" namespace to datasets

lib/Tuba/files/templates/table/object.ttl.tut
=> Added contributors for tables

lib/Tuba/files/templates/webpage/object.ttl.tut
=> Clarified that "date" means webpage "accessDate"

lib/Tuba/files/templates/doc/about.html.ep
=> Added JPL team

lib/Tuba/files/templates/article/object.html.ep, lib/Tuba/files/templates/book/object.html.ep, lib/Tuba/files/templates/report/object.html.ep, lib/Tuba/files/templates/webpage/object.html.ep
=> Ordered contributors

lib/Tuba.pm, lib/Tuba/files/public/test.html, t/002_basic.t
Changes suggested by a security scan, breaking frames and removing a test file (redirecting the test to a real page).
=> Master+gcis scan changes

lib/Tuba/files/templates/organization/object.ttl.tut
=> Added "unit of" as relationship type

lib/Tuba/files/templates/menu.html.ep, lib/Tuba/files/templates/opensearch.xml.ep
This is the fix for the issue [gcis-internal #13](https://github.com/USGCRP/gcis-internal/issues/13)
=> Updated to our new google CSE id

db/dist/base.sql, db/dist/docs/html/contents.html, db/dist/docs/html/view_gcis_metadata.vocabulary.html, db/dist/docs/pod/view_vocabulary.pod, db/dist/patches_applied.txt, db/patches/2260_add_vocabulary_view.sql, lib/Tuba.pm, lib/Tuba/Context.pm, lib/Tuba/Controller.pm, lib/Tuba/DB/Mixin/Object/Chapter/Manager.pm, lib/Tuba/DB/Mixin/Object/Figure/Manager.pm, lib/Tuba/DB/Mixin/Object/Finding/Manager.pm, lib/Tuba/DB/Mixin/Object/Report/Manager.pm, lib/Tuba/DB/Mixin/Object/Table/Manager.pm, lib/Tuba/DB/Mixin/Object/Term.pm, lib/Tuba/DB/Mixin/Object/Vocabulary.pm, lib/Tuba/DB/Object.pm, lib/Tuba/DB/Object/Manager.pm, lib/Tuba/DB/Objects.pm, lib/Tuba/Exterm.pm, lib/Tuba/Search.pm, lib/Tuba/Term.pm, lib/Tuba/Vocabulary.pm, lib/Tuba/files/templates/search/keyword.html.ep, lib/Tuba/files/templates/vocabulary/object.html.ep.still_broken_use_generic, lib/Tuba/files/templates/vocabulary/objects.html.ep
This includes changes for returning search counts referenced in #410
=> Merge changes for Search.pm and /vocabulary

lib/Tuba/Plugin/TubaHelpers.pm, lib/Tuba/files/templates/auth/login_key.html.ep, lib/Tuba/files/templates/finding/object.html.ep, lib/Tuba/files/templates/h/featured_reports.html.ep, lib/Tuba/files/templates/index.html.ep, lib/Tuba/files/templates/menu.html.ep
Small tweaks in support of the Climate Science Special Report's release
=> CSSR Preparatory Release - 1.51.1

README.docker.md, docker-compose.yml, lib/Tuba/Activity.pm, lib/Tuba/Array.pm, lib/Tuba/Controller.pm, lib/Tuba/DB/Mixin/Object/Publication.pm, lib/Tuba/DB/Object/Manager.pm, lib/Tuba/Figure.pm, lib/Tuba/Image.pm, lib/Tuba/Methodology.pm, lib/Tuba/Organization.pm, lib/Tuba/Person.pm, lib/Tuba/Table.pm
I located some more locations where the audit user and audit note parameters were not being passed to postgresql by the Tuba code. I modified a number of files to address the problem. There may be yet others, but I was unable to find them. Most of these relate to deleting entries. I also attempted to address a situation where the error arose during file upload.
=> Fixed more sources of audit user/note errors.
